In [29]:
import pandas as pd
import numpy as np
import os

import json

In [30]:
PATH_MOVIELENS = os.path.join('..','dataset','TMDB 5000')

In [31]:
movies = pd.read_csv(os.path.join(PATH_MOVIELENS,'tmdb_5000_credits.csv'),usecols=['movie_id','cast','crew'])
movie_info = pd.read_csv(os.path.join(PATH_MOVIELENS,'tmdb_5000_movies.csv'))
movies.head()

,movie_id,cast,crew
0,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [32]:
movie_info.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [33]:
movies_df = movies.merge(right=movie_info,left_on='movie_id',right_on='id',how='left')

In [34]:
movies_df.drop(columns='id',inplace=True)
movies_df.head()

,movie_id,cast,crew,budget,genres,homepage,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [35]:
movies_df.shape

(4803, 22)

In [36]:
# select released movies only.
movies_df = movies_df[movies_df['status'] == 'Released']

In [37]:
# content based filtering

# term frequency-inverse document frequency

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')

# replace nan with empty string
movies_df['overview_clean'] = movies_df['overview'].fillna('')

# construct the TF-IDF matrix
tfidf_matrix = tfidf.fit_transform(movies_df['overview_clean'])

tfidf_matrix.shape

(4795, 20970)

### Feature cleaning

In [38]:
(movies_df['overview'].str.len()).idxmin()

np.int64(4458)

In [39]:
movies_df.loc[2647,'overview']

"The photographer Leon lives with his girlfriend and waitress Maya waiting for a chance to get in the photo business. When Maya contacts their friend Jurgis, he schedules a meeting for Leon with the successful owner of arts gallery Susan Hoff; she analyzes Leon's work and asks him to improve the quality of his photos. During the night, the upset Leon decides to wander on the streets taking pictures with his camera, and he follows three punks down to the subway station; when the gang attacks a young woman, Leon defends her and the guys move on. On the next morning, Leon discovers that the woman is missing. He goes to the police station, but Detective Lynn Hadley does not give much attention to him and discredits his statement. Leon becomes obsessed to find what happened with the stranger and he watches the subway station. When he sees the elegant butcher Mahogany in the train, Leon believes he might be a murderer and stalks him everywhere, in the beginning of his journey to the darkness."

In [40]:
temp = movies_df['genres'][0]
temp

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [41]:
temp =  json.loads(temp)
temp

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [42]:
gen =[g['name'] for g in temp]
gen

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [43]:
' '.join(gen)

'Action Adventure Fantasy Science Fiction'

In [44]:
def process_genres(x):
    x = json.loads(x)
    genres = {g['name'] for g in x}
    result = " "+ ', '.join(genres)
    return result

# genres_clean =  movies_df['genres'].apply(process_genres)
movies_df['genres_clean'] =  movies_df['genres'].apply(process_genres)
movies_df['genres_clean'].head(2)

0     Science Fiction, Fantasy, Adventure, Action
1                      Fantasy, Action, Adventure
Name: genres_clean, dtype: str

In [45]:
# cast
def process_cast(x):
    '''
    x : input record
    '''
    main_cast = list(range(0,4))
    x = json.loads(x)
    cast_members = list()
    for cast in x:
        if cast['order'] in main_cast:
            cast_members.append(cast['name'].strip())

    result = " " + ', '.join(cast_members)
    return result
movies_df['cast_clean'] = movies_df['cast'].apply(process_cast)

In [48]:
# crews

def process_crew(x):

    x = json.loads(x)
    
    # imp_crew = ['Director','Writer', 'Cinematographer']
    # crew_members = []
    # director = ''
    result = ' '
    for crew in x:
        if crew['job'] == 'Director':
            # crew_members.append(f'{crew['job']} is {crew['name']}')
            result = f'Director: {crew['name']}'
            

    # result = " " + ', '.join(crew_members)
    return result
movies_df['crew_clean'] = movies_df['crew'].apply(process_crew)

'Director: James Cameron'

In [19]:
# keywords
def process_keywords(x):

    x  = json.loads(x)
    keywords = {k['name'] for k in x}

    result = " " + ', '.join(keywords)
    return result

movies_df['keywords_clean'] = movies_df['keywords'].apply(process_keywords)

In [20]:
movies_df['overview_clean'] =  movies_df['overview'].fillna(' ')

In [21]:
movies_df['overview_clean'].isna().sum()

np.int64(0)

In [22]:
movies_df['overview_clean'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [23]:
movies_df.info()

<class 'pandas.DataFrame'>
Index: 4795 entries, 0 to 4802
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movie_id              4795 non-null   int64
 1   cast                  4795 non-null   str
 2   crew                  4795 non-null   str
 3   budget                4795 non-null   int64
 4   genres                4795 non-null   str
 5   homepage              1709 non-null   str
 6   keywords              4795 non-null   str
 7   original_language     4795 non-null   str
 8   original_title        4795 non-null   str
 9   overview              4792 non-null   str
 10  popularity            4795 non-null   float64
 11  production_companies  4795 non-null   str
 12  production_countries  4795 non-null   str
 13  release_date          4794 non-null   str
 14  revenue               4795 non-null   int64
 15  runtime               4793 non-null   float64
 16  spoken_languages      4795 non-null   str
 17  status                4795 non-null   str
 18  tagline               3957 non-null   str
 19  title                 4795 non-null   str
 20  vote_average          4795 non-null   float64
 21  vote_count            4795 non-null   int64
 22  overview_clean        4795 non-null   str
 23  genres_clean          4795 non-null   str
 24  cast_clean            4795 non-null   str
 25  crew_clean            4795 non-null   str
 26  keywords_clean        4795 non-null   str
dtypes: float64(3), int64(4), str(20)
memory usage: 41.7 MB

In [24]:
movies_df['original_language'].unique()

<ArrowStringArray>
['en', 'ja', 'fr', 'zh', 'es', 'de', 'hi', 'ru', 'ko', 'te', 'cn', 'it', 'nl',
 'ta', 'sv', 'th', 'da', 'xx', 'hu', 'pt', 'is', 'tr', 'cs', 'nb', 'af', 'pl',
 'he', 'ar', 'vi', 'ky', 'id', 'ro', 'fa', 'no', 'sl', 'ps', 'el']
Length: 37, dtype: str

In [25]:
# hangling Original_language
language_map = {
    'en': 'English', 'ja': 'Japanese', 'fr': 'French', 'zh': 'Chinese', 'es': 'Spanish',
    'de': 'German', 'hi': 'Hindi', 'ru': 'Russian', 'ko': 'Korean', 'te': 'Telugu',
    'cn': 'Cantonese', 'it': 'Italian', 'nl': 'Dutch', 'ta': 'Tamil', 'sv': 'Swedish',
    'th': 'Thai', 'da': 'Danish', 'xx': 'Unknown', 'hu': 'Hungarian', 'cs': 'Czech',
    'pt': 'Portuguese', 'is': 'Icelandic', 'tr': 'Turkish', 'nb': 'Norwegian Bokmål',
    'af': 'Afrikaans', 'pl': 'Polish', 'he': 'Hebrew', 'ar': 'Arabic', 'vi': 'Vietnamese',
    'ky': 'Kyrgyz', 'id': 'Indonesian', 'ro': 'Romanian', 'fa': 'Persian', 'no': 'Norwegian',
    'sl': 'Slovenian', 'ps': 'Pashto', 'el': 'Greek'
}

# Replace the short form language with its full name.
movies_df['original_language_full'] = movies_df['original_language'].map(language_map)

In [26]:
# tagline
movies_df['tagline'] = movies_df['tagline'].fillna(' ')

In [27]:
pd.set_option('display.max_columns', None)

In [28]:
clean_df = movies_df.drop(columns = ['cast','crew','keywords','genres','original_language','overview','status'])
clean_df.to_csv('../dataset/processed/movies_df_clean.csv',index=False)